version: '3.8'

services:
  postgres:
    image: postgres
    container_name: mdms-postgres
    ports:
      - '5435:5432' # Change the host port to 5435
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mdms-development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
